apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: japl-hello
  annotations:
    version: v0.1.0
    description: "Hello World JAPL component on wasmCloud"
spec:
  components:
    - name: hello
      type: component
      properties:
        image: file:///tmp/hello_component.wasm
