export type Span = { start: number; end: number; line: number; col: number };

export enum TokenKind {
  // Literals
  Int,
  Float,
  String,
  True,
  False,

  // Identifiers
  Ident,
  UpperIdent,

  // Keywords (37)
  Fn,
  Let,
  Type,
  Match,
  If,
  Else,
  Trait,
  Impl,
  Module,
  Import,
  Pub,
  Opaque,
  Spawn,
  Send,
  Receive,
  Supervisor,
  Process,
  Test,
  Assert,
  Foreign,
  Unsafe,
  Use,
  Return,
  Done,
  Fail,
  Panic,
  Where,
  As,
  In,
  On,
  With,
  Strategy,
  Child,
  Resource,
  Continue,
  Property,
  Bench,

  // Operators
  Plus,
  Minus,
  Star,
  Slash,
  Percent,
  Eq,
  NotEq,
  Lt,
  Gt,
  LtEq,
  GtEq,
  And,
  Or,
  Not,
  Pipe,
  Compose,
  Concat,
  Arrow,
  FatArrow,
  Question,
  Assign,
  Bar,
  Dot,
  DotDot,
  Colon,
  ColonColon,
  Comma,
  Semicolon,
  Ampersand,

  // Delimiters
  LParen,
  RParen,
  LBrace,
  RBrace,
  LBracket,
  RBracket,

  // Special
  Newline,
  EOF,
  Comment,
}

export interface Token {
  kind: TokenKind;
  value: string;
  span: Span;
}

export const KEYWORDS: ReadonlyMap<string, TokenKind> = new Map<string, TokenKind>([
  ['fn', TokenKind.Fn],
  ['let', TokenKind.Let],
  ['type', TokenKind.Type],
  ['match', TokenKind.Match],
  ['if', TokenKind.If],
  ['else', TokenKind.Else],
  ['trait', TokenKind.Trait],
  ['impl', TokenKind.Impl],
  ['module', TokenKind.Module],
  ['import', TokenKind.Import],
  ['pub', TokenKind.Pub],
  ['opaque', TokenKind.Opaque],
  ['spawn', TokenKind.Spawn],
  ['send', TokenKind.Send],
  ['receive', TokenKind.Receive],
  ['supervisor', TokenKind.Supervisor],
  ['process', TokenKind.Process],
  ['test', TokenKind.Test],
  ['assert', TokenKind.Assert],
  ['foreign', TokenKind.Foreign],
  ['unsafe', TokenKind.Unsafe],
  ['use', TokenKind.Use],
  ['return', TokenKind.Return],
  ['done', TokenKind.Done],
  ['fail', TokenKind.Fail],
  ['panic', TokenKind.Panic],
  ['where', TokenKind.Where],
  ['as', TokenKind.As],
  ['in', TokenKind.In],
  ['on', TokenKind.On],
  ['with', TokenKind.With],
  ['strategy', TokenKind.Strategy],
  ['child', TokenKind.Child],
  ['resource', TokenKind.Resource],
  ['continue', TokenKind.Continue],
  ['property', TokenKind.Property],
  ['bench', TokenKind.Bench],
  ['true', TokenKind.True],
  ['false', TokenKind.False],
]);

const TOKEN_KIND_NAMES: Record<number, string> = {
  [TokenKind.Int]: 'Int',
  [TokenKind.Float]: 'Float',
  [TokenKind.String]: 'String',
  [TokenKind.True]: 'True',
  [TokenKind.False]: 'False',
  [TokenKind.Ident]: 'Ident',
  [TokenKind.UpperIdent]: 'UpperIdent',
  [TokenKind.Fn]: 'Fn',
  [TokenKind.Let]: 'Let',
  [TokenKind.Type]: 'Type',
  [TokenKind.Match]: 'Match',
  [TokenKind.If]: 'If',
  [TokenKind.Else]: 'Else',
  [TokenKind.Trait]: 'Trait',
  [TokenKind.Impl]: 'Impl',
  [TokenKind.Module]: 'Module',
  [TokenKind.Import]: 'Import',
  [TokenKind.Pub]: 'Pub',
  [TokenKind.Opaque]: 'Opaque',
  [TokenKind.Spawn]: 'Spawn',
  [TokenKind.Send]: 'Send',
  [TokenKind.Receive]: 'Receive',
  [TokenKind.Supervisor]: 'Supervisor',
  [TokenKind.Process]: 'Process',
  [TokenKind.Test]: 'Test',
  [TokenKind.Assert]: 'Assert',
  [TokenKind.Foreign]: 'Foreign',
  [TokenKind.Unsafe]: 'Unsafe',
  [TokenKind.Use]: 'Use',
  [TokenKind.Return]: 'Return',
  [TokenKind.Done]: 'Done',
  [TokenKind.Fail]: 'Fail',
  [TokenKind.Panic]: 'Panic',
  [TokenKind.Where]: 'Where',
  [TokenKind.As]: 'As',
  [TokenKind.In]: 'In',
  [TokenKind.On]: 'On',
  [TokenKind.With]: 'With',
  [TokenKind.Strategy]: 'Strategy',
  [TokenKind.Child]: 'Child',
  [TokenKind.Resource]: 'Resource',
  [TokenKind.Continue]: 'Continue',
  [TokenKind.Property]: 'Property',
  [TokenKind.Bench]: 'Bench',
  [TokenKind.Plus]: 'Plus',
  [TokenKind.Minus]: 'Minus',
  [TokenKind.Star]: 'Star',
  [TokenKind.Slash]: 'Slash',
  [TokenKind.Percent]: 'Percent',
  [TokenKind.Eq]: 'Eq',
  [TokenKind.NotEq]: 'NotEq',
  [TokenKind.Lt]: 'Lt',
  [TokenKind.Gt]: 'Gt',
  [TokenKind.LtEq]: 'LtEq',
  [TokenKind.GtEq]: 'GtEq',
  [TokenKind.And]: 'And',
  [TokenKind.Or]: 'Or',
  [TokenKind.Not]: 'Not',
  [TokenKind.Pipe]: 'Pipe',
  [TokenKind.Compose]: 'Compose',
  [TokenKind.Concat]: 'Concat',
  [TokenKind.Arrow]: 'Arrow',
  [TokenKind.FatArrow]: 'FatArrow',
  [TokenKind.Question]: 'Question',
  [TokenKind.Assign]: 'Assign',
  [TokenKind.Bar]: 'Bar',
  [TokenKind.Dot]: 'Dot',
  [TokenKind.DotDot]: 'DotDot',
  [TokenKind.Colon]: 'Colon',
  [TokenKind.ColonColon]: 'ColonColon',
  [TokenKind.Comma]: 'Comma',
  [TokenKind.Semicolon]: 'Semicolon',
  [TokenKind.Ampersand]: 'Ampersand',
  [TokenKind.LParen]: 'LParen',
  [TokenKind.RParen]: 'RParen',
  [TokenKind.LBrace]: 'LBrace',
  [TokenKind.RBrace]: 'RBrace',
  [TokenKind.LBracket]: 'LBracket',
  [TokenKind.RBracket]: 'RBracket',
  [TokenKind.Newline]: 'Newline',
  [TokenKind.EOF]: 'EOF',
  [TokenKind.Comment]: 'Comment',
};

export function tokenKindName(kind: TokenKind): string {
  return TOKEN_KIND_NAMES[kind] ?? 'Unknown';
}
